name: database
label: database
resource_label: database
description: database instance group for Prometheus tile

templates:
- $(job "postgres")

max_in_flight: 1
single_az_only: true

instance_definition:
  name: instances
  type: integer
  label: Instances
  configurable: true
  default: 1
  constraints: 
    min: 0
    max: 1

resource_definitions:
- name: ram
  type: integer
  label: RAM
  configurable: true
  default: 4096
  constraints:
    min: 4096

- name: ephemeral_disk
  type: integer
  label: Ephemeral Disk
  configurable: true
  default: 2000
  constraints:
    min: 2000

- name: persistent_disk
  type: integer
  label: Persistent Disk
  configurable: false
  default: 25000
  constraints:
    min: 25000

- name: cpu
  type: integer
  label: CPU
  configurable: true
  default: 2
  constraints: 
    min: 2
