name: prometheus
label: prometheus
resource_label: prometheus
description: prometheus instance group for Prometheus tile

templates:
- $(job "prometheus")

max_in_flight: 1
single_az_only: true

instance_definition:
  name: instances
  type: integer
  label: Instances
  configurable: true
  default: 1
  constraints: 
    min: 0
    max: 1

resource_definitions:
- name: ram
  type: integer
  label: RAM
  configurable: true
  default: 1024
  constraints:
    min: 1024

- name: ephemeral_disk
  type: integer
  label: Ephemeral Disk
  configurable: true
  default: 4000
  constraints:
    min: 1000

- name: persistent_disk
  type: integer
  label: Persistent Disk
  configurable: false
  default: 1024
  constraints:
    min: 1024

- name: cpu
  type: integer
  label: CPU
  configurable: true
  default: 1
  constraints: 
    min: 1
