name: prometheus
release: prometheus
manifest: |
  prometheus:
    rule_files:
      - /var/vcap/jobs/postgres_alerts/*.alerts*
      - /var/vcap/jobs/prometheus_alerts/*.alerts*
    scrape_configs:
      - job_name: prometheus
        static_configs:
        - targets:
          - localhost:9090
